# Generated by Django 2.2.6 on 2022-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20220213_2156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(verbose_name="Описание группы"),
        ),
    ]
